### ISSUE TITLE
Question: It can be used as a Git subcommand, as git forge.

### ISSUE THREAD

**Issue by jgarte** [srstevenson/git-forge#1]
>  It can be used as a Git subcommand, as git forge.

Hi, what currently enables this crate to be a `git` subcommand?

I didn't see any logic anywhere in the code base that sets that up 🙃

**Comment by srstevenson** [comment]
This is a feature of Git itself: if you call `git foo` where `foo` is not a builtin subcommand, Git will execute `git-foo` instead.

**Comment by jgarte** [comment]
Oh darn ,TIL. Thanks for the explanation! Much appreciated.
